const boardEl=document.getElementById("board"),statusEl=document.getElementById("status"),blackCapturedEl=document.getElementById("blackCaptured"),whiteCapturedEl=document.getElementById("whiteCaptured"),winnerOverlay=document.getElementById("winnerOverlay"),resetBtn=document.getElementById("reset"),startMenu=document.getElementById("startMenu"),gameScreen=document.getElementById("gameScreen"),startBtn=document.getElementById("startBtn"),fullscreenBtn=document.getElementById("fullscreenBtn"),whiteTimerEl=document.getElementById("whiteTimer"),blackTimerEl=document.getElementById("blackTimer"),whiteTimerBox=document.getElementById("whiteTimerBox"),blackTimerBox=document.getElementById("blackTimerBox"),timerOptions=document.querySelectorAll(".timer-option");
const symbols={w:{k:"♔",q:"♕",r:"♖",b:"♗",n:"♘",p:"♙"},b:{k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟"}},back=["r","n","b","q","k","b","n","r"];
let board,turn,selected,gameOver=false,selectedMinutes=null,timers={w:600,b:600},timerInterval=null,lastTick=0,captured={w:[],b:[]};
timerOptions.forEach(btn=>btn.addEventListener("click",()=>{timerOptions.forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");selectedMinutes=Number(btn.dataset.minutes);startBtn.disabled=false;}));
startBtn.addEventListener("click",()=>{startMenu.classList.add("hidden");gameScreen.classList.remove("hidden");startGame(selectedMinutes);});
function startGame(minutes){timers={w:minutes*60,b:minutes*60};newGame();startClock();}
function newGame(){stopClock();winnerOverlay.className="winner-overlay";winnerOverlay.innerHTML="";board=Array.from({length:8},()=>Array(8).fill(null));for(let c=0;c<8;c++){board[0][c]={color:"b",type:back[c]};board[1][c]={color:"b",type:"p"};board[6][c]={color:"w",type:"p"};board[7][c]={color:"w",type:back[c]};}turn="w";selected=null;gameOver=false;captured={w:[],b:[]};render();startClock();}
function startClock(){stopClock();lastTick=Date.now();timerInterval=setInterval(tickClock,250);updateTimers();}function stopClock(){if(timerInterval){clearInterval(timerInterval);timerInterval=null;}}function tickClock(){if(gameOver)return;const now=Date.now(),elapsed=(now-lastTick)/1000;lastTick=now;timers[turn]-=elapsed;if(timers[turn]<=0){timers[turn]=0;const winner=turn==="w"?"Black":"White";endByTime(winner);}updateTimers();}function updateTimers(){whiteTimerEl.textContent=formatTime(timers.w);blackTimerEl.textContent=formatTime(timers.b);whiteTimerBox.classList.toggle("active",!gameOver&&turn==="w");blackTimerBox.classList.toggle("active",!gameOver&&turn==="b");whiteTimerBox.classList.toggle("low",timers.w<=30);blackTimerBox.classList.toggle("low",timers.b<=30);}function formatTime(seconds){seconds=Math.ceil(Math.max(0,seconds));const m=Math.floor(seconds/60),s=seconds%60;return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function showWinner(winner, reason){
  statusEl.textContent=winner+" win — "+reason+"!";
  winnerOverlay.innerHTML=`<div class="winner-content"><div class="winner-message">${winner} win<br>— ${reason}! —</div><button id="overlayNewGame" class="overlay-new-game">New Game</button></div>`;
  winnerOverlay.classList.add("show");
  document.getElementById("overlayNewGame").onclick=()=>{timers={w:selectedMinutes*60,b:selectedMinutes*60};newGame();};
}
function endByTime(winner){gameOver=true;selected=null;stopClock();showWinner(winner,"Time");render();}
function findKing(color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]?.color===color&&board[r][c].type==="k")return{r,c};return null;}function isSquareAttacked(r,c,byColor){for(let sr=0;sr<8;sr++)for(let sc=0;sc<8;sc++){const p=board[sr][sc];if(!p||p.color!==byColor)continue;if(pieceAttacks(sr,sc,r,c))return true;}return false;}function pieceAttacks(sr,sc,tr,tc){const p=board[sr][sc],dr=tr-sr,dc=tc-sc,adr=Math.abs(dr),adc=Math.abs(dc);if(p.type==="p"){const dir=p.color==="w"?-1:1;return dr===dir&&adc===1;}if(p.type==="n")return(adr===2&&adc===1)||(adr===1&&adc===2);if(p.type==="k")return adr<=1&&adc<=1;if(p.type==="r")return(dr===0||dc===0)&&clearPath(sr,sc,tr,tc);if(p.type==="b")return adr===adc&&clearPath(sr,sc,tr,tc);if(p.type==="q")return(dr===0||dc===0||adr===adc)&&clearPath(sr,sc,tr,tc);return false;}function isInCheck(color){const k=findKing(color);return k?isSquareAttacked(k.r,k.c,color==="w"?"b":"w"):false;}
function pseudoLegal(sr,sc,tr,tc){const p=board[sr][sc];if(!p)return false;if(board[tr][tc]?.color===p.color)return false;const dr=tr-sr,dc=tc-sc,adr=Math.abs(dr),adc=Math.abs(dc);if(p.type==="p"){const dir=p.color==="w"?-1:1,start=p.color==="w"?6:1;if(dc===0&&!board[tr][tc]&&dr===dir)return true;if(dc===0&&sr===start&&dr===2*dir&&!board[sr+dir][sc]&&!board[tr][tc])return true;return adc===1&&dr===dir&&!!board[tr][tc]&&board[tr][tc].color!==p.color;}if(p.type==="n")return(adr===2&&adc===1)||(adr===1&&adc===2);if(p.type==="k")return adr<=1&&adc<=1;if(p.type==="r")return(dr===0||dc===0)&&clearPath(sr,sc,tr,tc);if(p.type==="b")return adr===adc&&clearPath(sr,sc,tr,tc);if(p.type==="q")return(dr===0||dc===0||adr===adc)&&clearPath(sr,sc,tr,tc);return false;}function clearPath(sr,sc,tr,tc){const stepR=Math.sign(tr-sr),stepC=Math.sign(tc-sc);let r=sr+stepR,c=sc+stepC;while(r!==tr||c!==tc){if(board[r][c])return false;r+=stepR;c+=stepC;}return true;}function isLegal(sr,sc,tr,tc){const p=board[sr][sc];if(!p||p.color!==turn||!pseudoLegal(sr,sc,tr,tc))return false;const captured=board[tr][tc];board[tr][tc]=p;board[sr][sc]=null;const safe=!isInCheck(p.color);board[sr][sc]=p;board[tr][tc]=captured;return safe;}function hasLegalMove(color){const oldTurn=turn;turn=color;for(let r=0;r<8;r++)for(let c=0;c<8;c++){if(board[r][c]?.color!==color)continue;for(let tr=0;tr<8;tr++)for(let tc=0;tc<8;tc++)if(isLegal(r,c,tr,tc)){turn=oldTurn;return true;}}turn=oldTurn;return false;}
function renderCaptured(){
  const draw=(el,color)=>{el.innerHTML="";for(const type of captured[color]){const span=document.createElement("span");span.className="captured-piece "+(color==="w"?"white-piece":"black-piece");span.textContent=symbols[color][type];el.appendChild(span);}};
  draw(blackCapturedEl,"b");draw(whiteCapturedEl,"w");
}
function render(){boardEl.innerHTML="";const checkColor=isInCheck(turn),mate=checkColor&&!hasLegalMove(turn);for(let r=0;r<8;r++)for(let c=0;c<8;c++){const sq=document.createElement("div");sq.className="square "+((r+c)%2?"dark":"light");const p=board[r][c];if(p&&p.type==="k"&&p.color===turn&&checkColor)sq.classList.add(mate?"checkmate":"check");if(selected&&selected.r===r&&selected.c===c)sq.classList.add("selected");if(selected&&!gameOver&&isLegal(selected.r,selected.c,r,c))sq.classList.add("valid");if(p){const span=document.createElement("span");span.className="piece "+(p.color==="w"?"white-piece":"black-piece");span.textContent=symbols[p.color][p.type];sq.appendChild(span);}sq.onclick=()=>clickSquare(r,c);boardEl.appendChild(sq);}if(mate){gameOver=true;stopClock();const winner=turn==="w"?"Black":"White";statusEl.textContent=winner+" win — Checkmate!";showWinner(winner,"Checkmate");}else if(checkColor)statusEl.textContent=(turn==="w"?"White":"Black")+" is in check!";else if(!gameOver)statusEl.textContent=(turn==="w"?"White":"Black")+"'s turn";renderCaptured();updateTimers();}
function clickSquare(r,c){if(gameOver)return;const p=board[r][c];if(!selected){if(p?.color===turn){selected={r,c};render();}return;}if(selected.r===r&&selected.c===c){selected=null;render();return;}if(p?.color===turn){selected={r,c};render();return;}if(isLegal(selected.r,selected.c,r,c)){movePiece(selected.r,selected.c,r,c);turn=turn==="w"?"b":"w";selected=null;render();}}
function movePiece(sr,sc,tr,tc){const p=board[sr][sc],capturedPiece=board[tr][tc];if(capturedPiece)captured[capturedPiece.color].push(capturedPiece.type);board[tr][tc]=p;board[sr][sc]=null;if(p.type==="p"&&(tr===0||tr===7))p.type="q";}
resetBtn.onclick=()=>{timers={w:selectedMinutes*60,b:selectedMinutes*60};newGame();};
fullscreenBtn.addEventListener("click",async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch(e){}});document.addEventListener("fullscreenchange",()=>{const active=!!document.fullscreenElement;document.documentElement.classList.toggle("fullscreen-active",active);fullscreenBtn.title=active?"Exit Full Screen":"Full Screen";});
